name: test

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      # Checkout the code.
      - uses: actions/checkout@v2
      # Activate python environment
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: build
        run: |
          python3 -m venv .
          bin/pip install -r requirements.txt
      - name: test
        run: make test
      - name: create packages
        run: bin/python setup.py sdist bdist_wheel