name: test

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code.
      - uses: actions/checkout@v2
      # Activate python environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: build
        run: |
          python3 -m venv .
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
          pip install GDAL
          bin/pip install -r requirements.txt
      - name: test
        run: make test
      - name: create packages
        run: bin/python setup.py sdist bdist_wheel
